* Installation
Big mess. Annoying order dependencies for installation of python
packages. Manual installs from git repos for racket json view, etc.

Consider using gentoo prefix on macos to manage the python deps, need
to retain the native racket on macos though, or figure out how to get
the gentoo ebuild to trigger a macos build instead of a linux based
build when in prefix, likely too much work and the long compile times
are bad for users.

* Configuration
Initial configuration is currently a mess, it needs to be managable
via the options window, and the initial updates to use sxpr files for
config so that configs are accessible across languages have been made,
but the switchover has not been completed yet.

1. google: use a services account read only json blob.
2. pennsieve key, secret
3. hypothes.is key
4. protocols.io key and more

* Reminders
Don't close the viewer terminal!

* Install
#+begin_src bash
group_repo=(tgbugs/pyontutils tgbugs/sxpyr tgbugs/augpathlib tgbugs/idlib tgbugs/hyputils tgbugs/orthauth tgbugs/ontquery tgbugs/parsercomb tgbugs/protc SciCrunch/sparc-curation)
pushd ~/git
for _gr in ${group_repo[@]}; do
git clone https://github.com/${_gr}.git;
done
popd;
#+end_src

#+begin_src bash
raco pkg install --name breadcrumb --type git-url https://github.com/tgbugs/racket-breadcrumb.git
raco pkg install --name json-view --type git-url https://github.com/tgbugs/racket-json-view.git
raco pkg install git/orthauth/racket/orthauth

pushd ~/git/sparc-curation/sparcur_internal
raco pkg install --auto --batch sparcur/
pushd sparcur
raco make viewer.rkt
raco exe viewer.rkt
popd; popd

# force creation of configuration files
python3 -m sparcur.cli
#+end_src

* Upgrading across racket versions, upgrading across python versions
Auto update mostly works until you get to a point where you have to update your racket version.
Then we are out of luck because the update has to fully succeed without any errors otherwise
the system will likely be left in a bad state.

** python
updating python versions is an even bigger nightmare due to the installation order issues
minimally it seems we need to install sparcur and pyontutils, but the ordering is still
bad news, don't forget to remove all the .egg-info folders first etc

on macos
#+begin_src bash
brew install python3
# and then manually
things_in_the_right_order=(pyontutils/clifn sxpyr augpathlib idlib pyontutils/htmlfn pyontutils/ttlser hyputils orthauth ontquery parsercomb pyontutils protc/protcur sparc-curation)
pushd ~/git
for folder in ${things_in_the_right_order[@]}; do
pushd ${folder};
pip3 install --user -e .;
popd;
done
popd
#+end_src

** racket
#+begin_src bash
brew update
brew upgrade

raco pkg migrate ${previous_version}
pushd ~/git/sparc-curation/sparcur_internal/sparcur
raco make viewer.rkt
raco exe viewer.rkt
popd
#+end_src

when adding a new local repo path e.g. orthauth
run the following before update
#+begin_src bash
pushd ~/git/orthauth
git pull
raco pkg install --batch --auto racket/orthauth
popd
# ~/git/orthauth/racket/orthauth doesn't work on windows for some reason?
#+end_src
TODO maybe we can tangle the bits of =setup.org= that we need?
or even run then via the shebang?
