from pathlib import Path

class config:
    organ_html_path = Path('../resources/sparc-nervous-system-graphic.html')  # FIXME include in distribution ...
    cache_dir = Path('~/files/sparcur-cache').expanduser()  # FIXME per user ...
